name: em_mobui
description: Mock Project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  elementary: ^3.0.0
  elementary_cli: ^2.0.0
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  encrypted_shared_preferences: ^3.0.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  dio: ^5.4.0
  elementary_helper: ^1.0.1
  mockito: ^5.4.4
  shimmer_animation: ^2.1.0+1
  flutter_svg: ^2.0.9
  decimal: ^2.3.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/

